rtc_time_drift_sec:
  min: 0
  max: 2
  unit: SECOND
  doc: "RTC time drift over power cycle"

ip_address:
  doc: "Must be valid IPv4"

accelerometer_present:
  equals: true

gyro_present:
  equals: true

accelerometer_events_3s:
  min: 50
  doc: "Number of accelerometer reports over time"

gyro_events_3s:
  min: 50
  doc: "Number of gyroscope reports over time"

num_keys:
  equals: 2
  doc: "Number of keys detected in device"

cpu_idle_percentage:
  min: 90
  unit: percent

cpu_load_avg:
  max: 20 #TODO: Change this, current bug causes spikes

cpu_temp:
  min: 20
  max: 40
  unit: "Â°C"

total_memory_kb:
  min: 1800000
  unit: kilobyte

left_cam_present:
  equals: true
  doc: "Verify if left cam present in v4l2"

right_cam_present:
  equala: true
  doc: "Verify if right cam present in v4l2"
